name: Sync Environment Variables to Railway

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "sync" to confirm syncing all environment variables to Railway'
        required: true
        default: ''

jobs:
  sync-railway:
    if: github.event.inputs.confirm == 'sync'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Sync environment variables to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          echo "🔄 Syncing environment variables to Railway..."

          # Authenticate with Railway
          railway login --browserless

          # Link to project
          railway link $RAILWAY_PROJECT_ID

          # Set environment variables
          # Railway CLI: railway variables set KEY=value

          # Supabase
          railway variables set SUPABASE_URL="${{ secrets.SUPABASE_URL }}"
          railway variables set SUPABASE_SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
          railway variables set SUPABASE_SECRET_KEY="${{ secrets.SUPABASE_SECRET_KEY }}"

          # OpenAI
          railway variables set OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"

          # Anthropic/Claude
          railway variables set ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}"

          # Deepgram
          railway variables set DEEPGRAM_API_KEY="${{ secrets.DEEPGRAM_API_KEY }}"

          # Braintrust
          railway variables set BRAINTRUST_API_KEY="${{ secrets.BRAINTRUST_API_KEY }}"

          # PocketCasts (if needed)
          railway variables set POCKETCASTS_EMAIL="${{ secrets.POCKETCASTS_EMAIL }}" || true
          railway variables set POCKETCASTS_PASSWORD="${{ secrets.POCKETCASTS_PASSWORD }}" || true

          echo "✅ Environment variables synced to Railway successfully!"

      - name: Summary
        if: success()
        run: |
          echo "✅ All environment variables have been synced to Railway"
          echo "🔗 Check your deployment at: https://railway.app/dashboard"
